[build]
  command = "npm install && npm run build && npx prisma generate"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  DATABASE_URL = "file:./prod.db"
  JWT_SECRET = "seu-jwt-secret-super-seguro-mude-em-producao-514742"
  JWT_EXPIRES_IN = "7d"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
