services:
  - type: web
    name: finantrack-api
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:[@Fillipe95@]@db.jhgehkehbclzkzrxehmg.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: finantrack_jwt_secret_2024_super_seguro_mude_em_producao_real
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: "*"
    healthCheckPath: /health
